// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | "/"
    | "/_locales/en/messages.json"
    | "/_locales/ja/messages.json"
    | "/assets/icon.png"
    | "/assets/icon_disabled.png"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/creturn-config.json"
    | "/options.html"
    | "/popup.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
